services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.uptime-kuma.rule=Host(`uptime.australianteamasters.com.au`)
      - traefik.http.routers.uptime-kuma.entrypoints=websecure
      - traefik.http.routers.uptime-kuma.tls.certresolver=letsencrypt
      - traefik.http.routers.uptime-kuma-http.rule=Host(`uptime.australianteamasters.com.au`)
      - traefik.http.routers.uptime-kuma-http.entrypoints=web
      - traefik.http.routers.uptime-kuma-http.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.services.uptime-kuma.loadbalancer.server.port=3001

volumes:
  uptime-kuma-data:

networks:
  dokploy-network:
    external: true
